"""tenant status enum and db-side timestamps

Revision ID: 392f7baf1ecb
Revises: c29d02d15eac
Create Date: 2026-09-27 00:26:43.459153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '392f7baf1ecb'
down_revision: Union[str, Sequence[str], None] = 'c29d02d15eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL enum type must exist before the column can use it.
    tenant_status = sa.Enum(
        "active",
        "suspended",
        "deleted",
        name="tenant_status",
    )
    tenant_status.create(op.get_bind(), checkfirst=True)

    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default='active',
               type_=sa.Enum('active', 'suspended', 'deleted', name='tenant_status'),
               existing_nullable=False,
               postgresql_using="status::tenant_status")
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'status',
               existing_type=sa.Enum('active', 'suspended', 'deleted', name='tenant_status'),
               server_default=None,
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using="status::varchar")

    tenant_status = sa.Enum(
        "active",
        "suspended",
        "deleted",
        name="tenant_status",
    )
    tenant_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
